title: QIN Mian 
logo: /assets/img/photo.jpg
description: Ph.D. Candidate
affiliation: The Chinese University of Hong Kong
email: mqin@link.cuhk.edu.hk
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
